SELECT * FROM BLINKIT_DATA;

/*Count number of rows in a table*/
SELECT COUNT(*) FROM BLINKIT_DATA;

/*Cleaning the Item_Fat_Content field ensures data consistency and accuracy in analysis. The presence of multiple variations of the same category (e.g., LF, low fat vs. Low Fat) can cause issues in reporting, aggregations, and filtering. By standardizing these values, we improve data quality, making it easier to generate insights and maintain uniformity in our datasets.*/
UPDATE BLINKIT_DATA
SET ITEM_FAT_CONTENT=
	CASE
		WHEN ITEM_FAT_CONTENT IN('LF','low fat') THEN 'Low Fat'
		WHEN ITEM_FAT_CONTENT ='reg' THEN 'Regular'
		ELSE ITEM_FAT_CONTENT
		END;

/*Check the data has been cleaned or not */
SELECT DISTINCT ITEM_FAT_CONTENT FROM BLINKIT_DATA;

/*TOTAL SALES*/
SELECT SUM(TOTAL_SALES) AS TOTAL_SALES FROM BLINKIT_DATA;

/*TOTAL SALES IN MILLION*/
SELECT CAST(SUM(TOTAL_SALES)/1000000 AS DECIMAL(10,2)) AS 
TOTAL_SALES_MILLION 
FROM BLINKIT_DATA;

/*TOTAL SALES LOW FAT CONTENT IN MILLION*/
SELECT CAST(SUM(TOTAL_SALES)/1000000 AS DECIMAL(10,2)) AS 
TOTAL_SALES_MILLION 
FROM BLINKIT_DATA
WHERE ITEM_FAT_CONTENT='LOW FAT';


/*TOTAL SALES IN YEAR 2022 IN MILLION*/
SELECT CAST(SUM(TOTAL_SALES)/1000000 AS DECIMAL(10,2)) AS 
TOTAL_SALES_MILLION 
FROM BLINKIT_DATA
WHERE OUTLET_ESTABLISHMENT_YEAR=2022;

/*AVERAGE SALES*/
SELECT AVG(TOTAL_SALES)AS AVG_SALES 
FROM BLINKIT_DATA;

/*AVERAGE SALES WHERE ITEM FAT CONTENT=LOW FAT*/
SELECT AVG(TOTAL_SALES)AS AVG_SALES 
FROM BLINKIT_DATA 
WHERE ITEM_FAT_CONTENT='LOW FAT';

/*AVERAGE SALES IN 2022*/
SELECT AVG(TOTAL_SALES)AS AVG_SALES 
FROM BLINKIT_DATA 
WHERE OUTLET_ESTABLISHMENT_YEAR=2022;

/*NUMBER OF ITEMS*/
SELECT COUNT(*) AS NUMBER_OF_ITEMS FROM BLINKIT_DATA;

/*AVERAGE RATING*/
SELECT CAST(AVG(RATING) AS DECIMAL(10,1))AS AVG_RATING 
FROM BLINKIT_DATA;

/*TOTAL SALES BY FAT CONTENT*/
SELECT ITEM_FAT_CONTENT, SUM(TOTAL_SALES) AS TOTAL_SALES 
FROM BLINKIT_DATA 
GROUP BY ITEM_FAT_CONTENT;

/*TOTAL SALES BY FAT CONTENT UPTO 2 DECIMAL */
SELECT ITEM_FAT_CONTENT, CAST (SUM(TOTAL_SALES) AS DECIMAL(10,2))AS TOTAL_SALES 
FROM BLINKIT_DATA 
GROUP BY ITEM_FAT_CONTENT;

/*FIND TOTAL SALES,AVERAGE SALES,COUNT OF ORDERS ,AVERAGE RATING OVER FAT CONTENT*/
SELECT ITEM_FAT_CONTENT,
		CAST (SUM(TOTAL_SALES) AS DECIMAL(10,2))AS TOTAL_SALES,
		CAST (AVG(TOTAL_SALES) AS DECIMAL(10,1))AS AVG_SALES,
		COUNT(*) AS NUMBER_OF_ORDERS,
		CAST(AVG(RATING)AS DECIMAL(10,2))AS AVG_RATING
FROM BLINKIT_DATA
GROUP BY ITEM_FAT_CONTENT;

/*FIND TOTAL SALES,AVERAGE SALES,COUNT OF ORDERS ,AVERAGE RATING OVER FAT CONTENT FOR OUTLET ESTABLISHMENT YEAR 2020 */
SELECT ITEM_FAT_CONTENT,
		CAST (SUM(TOTAL_SALES) AS DECIMAL(10,2))AS TOTAL_SALES,
		CAST (AVG(TOTAL_SALES) AS DECIMAL(10,1))AS AVG_SALES,
		COUNT(*) AS NUMBER_OF_ORDERS,
		CAST(AVG(RATING)AS DECIMAL(10,2))AS AVG_RATING
FROM BLINKIT_DATA
WHERE OUTLET_ESTABLISHMENT_YEAR=2020
GROUP BY ITEM_FAT_CONTENT;

/*TOTAL SALE BY ITEM TYPE*/
SELECT ITEM_TYPE, 
	CAST (SUM(TOTAL_SALES) AS DECIMAL(10,2)) TOTAL_SALES 
FROM BLINKIT_DATA
GROUP BY ITEM_TYPE;

/*FIND TOTAL SALES,AVERAGE SALES,COUNT OF ORDERS ,AVERAGE RATING OVER FAT CONTENT FOR ITEM TYPE */
SELECT ITEM_TYPE,
	CAST(SUM(TOTAL_SALES)AS DECIMAL(10,2))AS TOTAL_SALES ,
	CAST (AVG(TOTAL_SALES) AS DECIMAL(10,1))AS AVG_SALES,
	COUNT(*) AS NUMBER_OF_ORDERS,
	CAST(AVG(RATING)AS DECIMAL(10,2))AS AVG_RATING
FROM BLINKIT_DATA
GROUP BY ITEM_TYPE
ORDER BY TOTAL_SALES DESC;

/*FIND TOP 5 TOTAL SALES,AVERAGE SALES,COUNT OF ORDERS ,AVERAGE RATING OVER FAT CONTENT FOR ITEM TYPE */
SELECT TOP 5 ITEM_TYPE,
	CAST(SUM(TOTAL_SALES)AS DECIMAL(10,2))AS TOTAL_SALES ,
	CAST (AVG(TOTAL_SALES) AS DECIMAL(10,1))AS AVG_SALES,
	COUNT(*) AS NUMBER_OF_ORDERS,
	CAST(AVG(RATING)AS DECIMAL(10,2))AS AVG_RATING
FROM BLINKIT_DATA
GROUP BY ITEM_TYPE
ORDER BY TOTAL_SALES DESC;

/*FAT CONTENT BY OUTLET FOR TOTAL SALES*/
SELECT OUTLET_LOCATION_TYPE ,ITEM_FAT_CONTENT,
	CAST(SUM(TOTAL_SALES)AS DECIMAL(10,2))AS TOTAL_SALES 
FROM BLINKIT_DATA
GROUP BY OUTLET_LOCATION_TYPE,ITEM_FAT_CONTENT
ORDER BY TOTAL_SALES DESC;
	
/*FAT CONTENT BY OUTLET FOR TOTAL SALES*/
SELECT OUTLET_LOCATION_TYPE,
	ISNULL([LOW FAT],0)AS LOW_FAT,
	ISNULL([REGULAR],0)AS REGULAR
FROM
(	SELECT OUTLET_LOCATION_TYPE,ITEM_FAT_CONTENT,
	CAST(SUM(TOTAL_SALES)AS DECIMAL(10,2))AS TOTAL_SALES
	FROM BLINKIT_DATA
	GROUP BY OUTLET_LOCATION_TYPE,ITEM_FAT_CONTENT
) AS SOURCE_TABLE
PIVOT
(
	SUM(TOTAL_SALES)
	FOR ITEM_FAT_CONTENT IN([LOW FAT],[REGULAR])
)AS PIVOTTABLE
ORDER BY OUTLET_LOCATION_TYPE;

/*TOTAL SALES BY OUTLET ESTABLISHMENT*/
SELECT OUTLET_ESTABLISHMENT_YEAR,
		CAST(SUM(TOTAL_SALES)AS DECIMAL(10,2))AS TOTAL_SALES
FROM BLINKIT_DATA
GROUP BY OUTLET_ESTABLISHMENT_YEAR
ORDER BY OUTLET_ESTABLISHMENT_YEAR;

/*PERCENTAGE OF SALES BY OUTLET SIZE*/
SELECT 
	OUTLET_SIZE,
	CAST(SUM(TOTAL_SALES)AS DECIMAL(10,2))AS TOTAL_SALES,
	CAST((SUM(TOTAL_SALES)*100.0/SUM(SUM(TOTAL_SALES)) OVER ())AS DECIMAL(10,2))AS SALES_PERCENTAGE
FROM BLINKIT_DATA
GROUP BY OUTLET_SIZE
ORDER BY TOTAL_SALES DESC;

/*SALES BY OUTLET LOCATION*/
SELECT OUTLET_LOCATION_TYPE,
		CAST(SUM(TOTAL_SALES)AS DECIMAL(10,2))AS TOTAL_SALES 
FROM BLINKIT_DATA
GROUP BY Outlet_Location_Type
ORDER BY TOTAL_SALES DESC;

/*ALL METRICS BY OUTLET TYPE*/
SELECT Outlet_Type,
		CAST(SUM(Total_Sales)AS DECIMAL(10,2))AS TOTAL_SALES,
		CAST(AVG(Total_Sales)AS DECIMAL(10,0))AS AVG_SALES, 
		COUNT(*) AS NUMBER_OF_ITEMS,
		CAST(AVG(RATING)AS DECIMAL(10,2))AS AVG_RATING,
		CAST(AVG(ITEM_VISIBILITY)AS DECIMAL(10,2))AS ITEM_VISIBILITY 

FROM BLINKIT_DATA
GROUP BY OUTLET_TYPE
ORDER BY TOTAL_SALES DESC;
